# Generated by Django 4.2.13 on 2024-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_product', models.IntegerField(blank=True, null=True, verbose_name='Id Producto')),
                ('name_product', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nompre del Producto')),
                ('stock_product', models.IntegerField(blank=True, default=100, null=True, verbose_name='Stock del Producto')),
            ],
        ),
    ]
