# Generated by Django 4.2.13 on 2024-06-26 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approject3b', '0002_products_id_user_products_user_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_product', models.IntegerField(blank=True, null=True, verbose_name='Id Producto')),
                ('name_product', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nompre del Producto')),
                ('user_save', models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuario que Compro')),
                ('id_user', models.IntegerField(blank=True, null=True, verbose_name='Id Usuario')),
                ('fecha_order', models.DateField(default=datetime.datetime(2024, 6, 26, 0, 50, 26, 393166), verbose_name='Fecha de compra')),
                ('cant_order', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Compra')),
            ],
        ),
    ]
