# Generated by Django 4.2.13 on 2024-06-26 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approject3b', '0003_historyorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyorder',
            old_name='sku_product',
            new_name='idproduct',
        ),
        migrations.RenameField(
            model_name='historyorder',
            old_name='name_product',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='historyorder',
            old_name='id_user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='historyorder',
            old_name='user_save',
            new_name='userproduct',
        ),
        migrations.AlterField(
            model_name='historyorder',
            name='fecha_order',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 26, 0, 57, 4, 20384), null=True, verbose_name='Fecha de compra'),
        ),
    ]
